name: Publish to dist branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Read version from package.json
        id: pkg
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check
        run: |
          if git rev-parse "v${{ steps.pkg.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag already exists, skipping tag creation."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy dist folder to dist-only branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create orphan branch for dist-only
          git checkout --orphan dist-only
          git reset --hard
          git clean -fd

          # Copy built files from dist/
          cp -r dist/* .

          # Commit and push dist-only branch
          git add .
          git commit -m "Deploy version v${{ steps.pkg.outputs.version }}"
          git push origin dist-only --force

      - name: Tag this version
        if: steps.check.outputs.exists == 'false'
        run: |
          git tag v${{ steps.pkg.outputs.version }}
          git push origin v${{ steps.pkg.outputs.version }}
